<Project Sdk="Godot.NET.Sdk/4.5.1">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DefaultItemExcludes>$(DefaultItemExcludes);decompiled\**</DefaultItemExcludes>
  </PropertyGroup>

  <!-- Replace the path below with your actual STS2 path if it is different -->
  <ItemGroup>
    <Reference Include="sts2">
      <HintPath>.\sts2.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Alchyr.Sts2.BaseLib" Version="*" />
    <PackageReference Include="Lib.Harmony" Version="2.3.3" />
  </ItemGroup>
</Project>
